name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # You can specify 3.8 or 3.10 depending on your requirements

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pytest

    - name: Run tests
      run: |
        pytest
